apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: chilkuri1296/main:12
        ports:
        - containerPort: 80
