apiVersion: v1
kind: Service
metadata:
  name: my-web-poc
  labels:
    app: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31256
    protocol: TCP
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: chilkuri1296/newpoc
        ports:
        - containerPort: 80
